### ISSUE TITLE
Twitter send photo and messaging photos do not work

### ISSUE THREAD

**Issue by JohnnyS** [Re-Ignited-Development/Re-Ignited-Phone#154] opened 2021-09-19 02:23 UTC
I am trying to have it where you can send pictures through twitter and messages but it is not working, I do not see documentation on how to make this work aside from have screenshot basic and enable the option but nothing else from that works?

What are the exact steps I need to do?

I do have screenshot basic installed

**Comment by JohnnyS** [comment] 2021-09-19 02:38
I can make it upload to a discord webhook by changing the config.json but it doesn't post to twitter or anything
![image](https://user-images.githubusercontent.com/62607662/133913563-a96df0ed-bf0e-4ef1-9166-c1d28379aa7d.png)

**Comment by ThatPool** [comment] 2021-09-23 06:57
_in client/client.lua_

search for **takephoto**

and look for this code:
```
elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
	exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
            local resp = json.decode(data)
            DestroyMobilePhone()
            CellCamActivate(false, false)
            --cb(json.encode({ url = resp.files[1].url }))   
           cb(json.encode({ url = resp.url }))
        end)
        takePhoto = false
end
```

replace **it** with this:
```
elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
	exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
            local resp = json.decode(data)
            DestroyMobilePhone()
            CellCamActivate(false, false)
            --cb(json.encode({ url = resp.files[1].url }))   
           cb(json.encode({ url = resp.attachments[1].proxy_url }))
        end)
        takePhoto = false
end
```

_html/static/config/config.json_
![image](https://user-images.githubusercontent.com/63418483/134465834-b7466a66-f85a-40af-86fa-50e7ccb066eb.png)


it fixed for me. hope it fixes for you too

**Comment by JohnnyS** [comment] 2021-09-23 15:22
Aye thanks man that worked but I have it where the chat also shows tweets so it shows this in the chat
![image](https://user-images.githubusercontent.com/62607662/134536002-998593d5-ca82-4fdd-8a42-5c9aa7025b50.png)

Think there is anything I can do to filter that out? @ThatPool

**Comment by JohnnyS** [comment] 2021-09-23 15:22
Then the webhook has 
![image](https://user-images.githubusercontent.com/62607662/134536174-f91f5f4d-ab2b-41d4-a8a6-2da399349bcf.png)

**Comment by ThatPool** [comment] 2021-09-23 15:33
you'll have to modify the chat to work with it i suppose. may i ask what chat script you are using ?

and for discord log, it does work for me
![image](https://user-images.githubusercontent.com/63418483/134537880-f1a871f3-0ac7-4e6e-a98d-f8c9c573433a.png)

**Comment by JohnnyS** [comment] 2021-09-23 15:40
Its just esx rp chat and the regular chat but gcphone was modified to show tweets in the chat in the server/twitter.lua

`--[[ Orig but this doesnt show it on chat
RegisterServerEvent('gcPhone:twitter_postTweets')
AddEventHandler('gcPhone:twitter_postTweets', function(username, password, message)
  local _source = source
  local sourcePlayer = tonumber(_source)
  local srcIdentifier = ESX.GetPlayerFromId(_source).identifier
  TwitterPostTweet(username, password, message, sourcePlayer, srcIdentifier)
end)
]]
RegisterServerEvent('gcPhone:twitter_postTweets')
AddEventHandler('gcPhone:twitter_postTweets', function(username, password, message)
  local _source = source
  local sourcePlayer = tonumber(source)
  local srcIdentifier = ESX.GetPlayerFromId(_source).identifier
  TwitterPostTweet(username, password, message, sourcePlayer, srcIdentifier)
  TriggerClientEvent('chat:addMessage', -1, {
      template = '<div style="padding: 0.5vw; margin: 0.5vw; background-color: rgba(28, 160, 242, 0.6); border-radius: 3px;"><i class="fab fa-twitter"></i> @{0}:<br> {1}</div>',
      args = { username, message }
  })
end)`

Hmm for me it doesn't seems weird

**Comment by ThatPool** [comment] 2021-09-23 16:16
![image](https://user-images.githubusercontent.com/63418483/134544888-6c00704a-3793-4370-8311-0392c3e2d6b3.png)
![image](https://user-images.githubusercontent.com/63418483/134544957-11184b83-1527-450b-816b-a9c1a774e167.png)

```
RegisterServerEvent('gcPhone:twitter_postTweets')
AddEventHandler('gcPhone:twitter_postTweets', function(username, password, message)
  local _source = source
  local sourcePlayer = tonumber(_source)
  local srcIdentifier = ESX.GetPlayerFromId(_source).identifier
  TwitterPostTweet(username, password, message, sourcePlayer, srcIdentifier)

  if string.starts(message, "https://media.discordapp.net/attachments") then
    TriggerClientEvent('chat:addMessage', -1, {
      template = '<div style="padding: 0.5vw; margin: 0.5vw; background-color: rgba(28, 160, 242, 0.6); border-radius: 3px;"><i class="fab fa-twitter"></i> @{0}:<br><img src={1} style="margin: 0.5vw; border-radius:3px" width="333" height="200"></div>',
      args = { username, message }
    })
  else
    TriggerClientEvent('chat:addMessage', -1, {
      template = '<div style="padding: 0.5vw; margin: 0.5vw; background-color: rgba(28, 160, 242, 0.6); border-radius: 3px;"><i class="fab fa-twitter"></i> @{0}:<br> {1}</div>',
      args = { username, message }
    })
  end
end)

function string.starts(String,Start)
  return string.sub(String,1,string.len(Start))==Start
end

```

**Comment by JohnnyS** [comment] 2021-09-23 16:48
Dude Thanks so much looks like it works! The discord webhook though still doesn't, I changed it so it would show as it only showed when people had a avatar setup so I commented out some functions you think that might be the issue?

**Comment by ThatPool** [comment] 2021-09-23 16:56
I only noticed just now that your twitter logs won't go through unless you have avatar. so if you are done with the topic you may close it

**Comment by JohnnyS** [comment] 2021-09-23 17:06
No worries I mean you helped greatly last question if you would know where in the script it sets the default avatar when you create a twitter account?

**Comment by ThatPool** [comment] 2021-09-23 17:33
i dont think it will work. default avatar is already a picture that is in the \html\static\img\twitter\default_profile.png

this code can be found in the app.js which i really dont suggest you to edit unless you know what you are doing
`avatarUrl: "/html/static/img/twitter/default_profile.png"`

when you click the create account button it triggers nui callback in client side twitter.lua which have a default avatar png
which then sent to server side twitter.lua to create your account in database

but hey, i think i fixed the issue. 
i saw the http request error number 400 on server console which shows theres something wrong with the client side
and then here comes the image that is in the folder whos location was set in the code like this:
`/html/static/img/twitter/default_profile.png`
`["icon_url"] = tweet.authorIcon,`
and then http gets confused because it couldnt find the player avatar link as it was in the folder and not on http server.

`print("author icon",tweet.authorIcon)`
![image](https://user-images.githubusercontent.com/63418483/134555412-685f4c72-3f6d-4ce8-9b3d-7b276501a1e6.png)

so only way i made it work was to upload the default avatar png to http server like discord (you can use any as long as it gives you link in .png .jpg) and copy the image link

now open app.js and search for "/html/static/img/twitter/default_profile.png"
and replace it with the image link
![image](https://user-images.githubusercontent.com/63418483/134555814-f8ce5ba1-1c99-4269-875f-365b85712db2.png)

and there you have the message appearing with default avatar
![image](https://user-images.githubusercontent.com/63418483/134555877-14e6e93b-dc86-44db-86ea-3a13abe36f15.png)

sorry i have gone crazy in giving details even though i know that i am really not good at explaining stuff but here you go. hope it helps

**Comment by JohnnyS** [comment] 2021-09-23 18:10
Thank you so much man !!!!! This is amazing going to try it out for further testing but so far it looks like it is working

**Comment by ThatPool** [comment] 2021-09-23 18:12
cool. good luck

**Comment by JohnnyS** [comment] 2021-09-23 18:13
This may be a bit too much but was wondering since you been helping so much. Do you think there is a way to show the steam name in the logs next to the twitter name?

**Comment by ThatPool** [comment] 2021-09-23 18:22
you'll have to pass the parameter 'sourcePlayer' from this function
![image](https://user-images.githubusercontent.com/63418483/134562355-4611923b-5452-4c6b-8510-9fea93f452bb.png)

and edit the webhook data as follows
```
local data = {
    {
      ["color"] = "1942002",
      ["title"] = _U('new_tweet'),
      ["footer"] = {
          ["text"] = tweet.author.."("..ESX.GetPlayerFromId(sourcePlayer).getIdentifier()..")",
          ["icon_url"] = tweet.authorIcon,
      },
    }
  }
```

**Closed** 2021-09-23 18:42 UTC

**Comment by Brutuss** [comment] 2021-09-28 18:43
> 
> 
> _in client/client.lua_
> 
> search for **takephoto**
> 
> and look for this code:
> 
> ```
> elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
> 	exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
>             local resp = json.decode(data)
>             DestroyMobilePhone()
>             CellCamActivate(false, false)
>             --cb(json.encode({ url = resp.files[1].url }))   
>            cb(json.encode({ url = resp.url }))
>         end)
>         takePhoto = false
> end
> ```
> 
> replace **it** with this:
> 
> ```
> elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
> 	exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
>             local resp = json.decode(data)
>             DestroyMobilePhone()
>             CellCamActivate(false, false)
>             --cb(json.encode({ url = resp.files[1].url }))   
>            cb(json.encode({ url = resp.attachments[1].proxy_url }))
>         end)
>         takePhoto = false
> end
> ```
> 
> _html/static/config/config.json_ ![image](https://user-images.githubusercontent.com/63418483/134465834-b7466a66-f85a-40af-86fa-50e7ccb066eb.png)
> 
> it fixed for me. hope it fixes for you too

Could you please help me with this to :) ? I have everything installed. The phone is working, screenshot-basic runs (no edits done there). 

When using the phone in Twitter I can't get out of the camera app when clicking "Left mouse" or "ENTER" it looks like its making a picture but nothing happens and I can't get out with "Right mouse" or "ESCAPE". So need to restart the gcphone resource to get out of the camera lock. 

When using the camera app I can left click and then right click and am back. But also nothing happens. 

Done all the steps from your post. I don't see any errors in the logs and F8 also nothing in Discord. 

Hope you are willing to help :) 

Greetings!

**Comment by ThatPool** [comment] 2021-09-28 19:15
@Brutuss does it happens only in twitter or sending photo in direct message bugs too?

**Comment by JohnnyS** [comment] 2021-09-28 19:24
> > _in client/client.lua_
> > search for **takephoto**
> > and look for this code:
> > ```
> > elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
> > 	exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
> >             local resp = json.decode(data)
> >             DestroyMobilePhone()
> >             CellCamActivate(false, false)
> >             --cb(json.encode({ url = resp.files[1].url }))   
> >            cb(json.encode({ url = resp.url }))
> >         end)
> >         takePhoto = false
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > replace **it** with this:
> > ```
> > elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
> > 	exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
> >             local resp = json.decode(data)
> >             DestroyMobilePhone()
> >             CellCamActivate(false, false)
> >             --cb(json.encode({ url = resp.files[1].url }))   
> >            cb(json.encode({ url = resp.attachments[1].proxy_url }))
> >         end)
> >         takePhoto = false
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _html/static/config/config.json_ ![image](https://user-images.githubusercontent.com/63418483/134465834-b7466a66-f85a-40af-86fa-50e7ccb066eb.png)
> > it fixed for me. hope it fixes for you too
> 
> Could you please help me with this to :) ? I have everything installed. The phone is working, screenshot-basic runs (no edits done there).
> 
> When using the phone in Twitter I can't get out of the camera app when clicking "Left mouse" or "ENTER" it looks like its making a picture but nothing happens and I can't get out with "Right mouse" or "ESCAPE". So need to restart the gcphone resource to get out of the camera lock.
> 
> When using the camera app I can left click and then right click and am back. But also nothing happens.
> 
> Done all the steps from your post. I don't see any errors in the logs and F8 also nothing in Discord.
> 
> Hope you are willing to help :)
> 
> Greetings!

This doesn't happen with me double check if something gets missed

**Comment by Brutuss** [comment] 2021-09-28 19:32
> 
> 
> @Brutuss does it happens only in twitter or sending photo in direct message bugs too?

When sending a message to another person same behavior :(

**Comment by ThatPool** [comment] 2021-09-28 19:39
you did not followed the instructions correctly I suppose. If there are no errors how will I know the cause to fix it. Can you send your whole RegisterNUICallback('takePhoto') function here?

**Comment by Brutuss** [comment] 2021-09-28 19:51
I understand... thats why I am looking for a solution ;) Thnx for helping so far. Here is the funtion:

`RegisterNUICallback('takePhoto', function(data, cb)
	CreateMobilePhone(1)
  CellCamActivate(true, true)
  takePhoto = true
  Citizen.Wait(0)
  if hasFocus == true then
    SetNuiFocus(false, false)
    hasFocus = false
  end
	while takePhoto do
    Citizen.Wait(0)

		if IsControlJustPressed(1, 27) then -- Toogle Mode
			frontCam = not frontCam
			CellFrontCamActivate(frontCam)
    elseif IsControlJustPressed(1, 177) then -- CANCEL
      DestroyMobilePhone()
      CellCamActivate(false, false)
      cb(json.encode({ url = nil }))
      takePhoto = false
      break
	elseif IsControlJustPressed(1, 176) then -- TAKE.. PIC
		exports['screenshot-basic']:requestScreenshotUpload(data.url, data.field, function(data)
            local resp = json.decode(data)
            DestroyMobilePhone()
            CellCamActivate(false, false)
            --cb(json.encode({ url = resp.files[1].url }))   
           cb(json.encode({ url = resp.attachments[1].proxy_url }))
        end)
        takePhoto = false
	end
		HideHudComponentThisFrame(7)
		HideHudComponentThisFrame(8)
		HideHudComponentThisFrame(9)
		HideHudComponentThisFrame(6)
		HideHudComponentThisFrame(19)
    HideHudAndRadarThisFrame()
  end
  Citizen.Wait(1000)
  PhonePlayAnim('text', false, true)
end)`

**Comment by ThatPool** [comment] 2021-09-28 21:34
Can you open a new ticket and explain what things you tried and what is happening right now and share your code? maybe someone out there could help you if they have any clue. this is closed ticket so none probably going to see your messages except the ones that participated in it. Thankyou

**Comment by Brutuss** [comment] 2021-09-29 11:03
Ok will do that. Thnx for your help. Hope someone else can help me fixing the problem.
