### ISSUE TITLE
GcPhone not sending calls or any alerts.

### ISSUE THREAD

**Issue by Adrianmcmastergaming** [Re-Ignited-Development/Re-Ignited-Phone#137] opened 2021-06-28 18:02 UTC
Hi I have all the latest esx 1.2 legacy files but for some reason when folks die and press G ambulance folk do not get an alert. also when folks try phone one another the phone do not ring. 

I can see this in the server addonsgcphone-s.lua
AddEventHandler('esx_phone:registerNumber', function(number, type, sharePos, hasDispatch, hideNumber, hidePosIfAnon)
  print('= INFO = Registered number for ' .. number .. ' => ' .. type)
	local hideNumber    = hideNumber    or false
	local hidePosIfAnon = hidePosIfAnon or false

	PhoneNumbers[number] = {
		type          = type,
    sources       = {},
    alerts        = {}
	}
end)

I can also see this in the ambulancejob lua
TriggerEvent('esx_phone:registerNumber', 'ambulance', _U('alert_ambulance'), true, true)

so it is supposed to be sending an alert but there is no handshake.  So needs fixing ASAP.

**Comment by BTNGaming** [comment] 2021-07-01 05:52
You need to add the alert to esx_ambulancejob manually, We can't do that on our end, but you just need to add the code to it.

Find this
```lua
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)

	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_phone:send', 'ambulance', _U('distress_message'), false, {
		x = coords.x,
		y = coords.y,
		z = coords.z
	})
end
```

And replace with this:
```lua
function SendDistressSignal()
	local playerPed = PlayerPedId()
	PedPosition		= GetEntityCoords(playerPed)
	
	local PlayerCoords = { x = PedPosition.x, y = PedPosition.y, z = PedPosition.z }

	ESX.ShowNotification(_U('distress_sent'))

    TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), PlayerCoords, {

		PlayerCoords = { x = PedPosition.x, y = PedPosition.y, z = PedPosition.z },
	})
end
```

**Comment by Smokeprofit** [comment] 2021-08-07 01:37
Did you solve the people not being able to ring people? Everything in my phone works perfect except we cant make calls.

**Comment by Adrianmcmastergaming** [comment] 2021-08-07 06:05
No Mine is the same as yours everything works but cannot make any calls and send alerts to ems. It's a pain in the arse because there is no other phone out there for ESX 1.2 / 1.3 Legacy.  I have tried everything and am not sure what else to do.  I have had other devs who understand the Lua code look at it and they are not sure. I suspect it's something to do with the way es_extended uses the netevents, callbacks, triggerevents, feuntions, and other trigers. If the phone is designed for esx 1.1 then it is a big problem because the sql table has changed in the user's table so I think that's where it not fetching data somewhere because I could see something in the script that I could almost make sense were fetched the user information in a table no longer present.  Question is did the developer change it so it now uses the rockstar licence from the sql now called identifier that used to be steam id. That's something I could see in the script trying to fetch the user's id known as steam id. It is the script that will be sending calls, alerts and texts to the user's id but they will not receive anything because it is no longer there and replaced with the identifier. I am not a coder so no idea what to do about it.

**Comment by badchulo** [comment] 2021-08-09 16:48
Start gcphone before any job, is working perfectly for me

**Comment by Smokeprofit** [comment] 2021-08-10 06:21
Make sure you enter this in your esx_ambulance client.lua      search for distress
function SendDistressSignal()
	local playerPed = PlayerPedId()
	PedPosition		= GetEntityCoords(playerPed)
	
	local PlayerCoords = { x = PedPosition.x, y = PedPosition.y, z = PedPosition.z }

	ESX.ShowNotification(_U('distress_sent'))

    TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), PlayerCoords, {

		PlayerCoords = { x = PedPosition.x, y = PedPosition.y, z = PedPosition.z },
	})
end

**Comment by BTNGaming** [comment] 2021-08-14 19:51
If this is not working for you, Replace your Ambulancejob, As we have tested a few things to find that this was the cause. I will close this, this week if no reply.

**Comment by timonation** [comment] 2021-08-22 15:49
i have the same issue but messages works but dont calls do that. i use v1final and the correct version of your pphone

**Comment by Adrianmcmastergaming** [comment] 2021-09-05 23:15
I am still having problems with the Re-Ignited-Phone. I have used the 1.2 for because my framework is ESX 1.2 Legacy.  We tested it on our server and we can send text messages to one another. GPS but works sometimes but fails and not sure why.  We cannot receive phone calls from phone to phone.  I noticed you last updated on12/21/2020.  So the question is compatibility with ESX Legacy. I am aware since ESX 1.2 final was created ESX has changed a lot. ESX 1.2 Legacy is different. I can also see from comment other are having the same issue as me.  I have spoken to the ESX team and they say not sure about compatibility and should ask the developer. I am not a coder so no idea how to update myself but think you might need to make a few updates so its also compatible with ESX 1.2 Legacy because some server owner are upgrading to ESX 1.2 Legacy and having the same problems. There are no other phone mods out there that work with ESX Legacy cos I have tried them all. The default esx_phone works.  Me and a lot of other would-be grateful if it could be updated This is the link for ESX 1.2 Legacy created by the esx team. https://github.com/esx-framework/esx-legacy

**Comment by Adrianmcmastergaming** [comment] 2021-09-05 23:17
> i have the same issue but messages works but dont calls do that. i use v1final and the correct version of your pphone

Mine is is the same and been like that since June. I have tried everything.  Its just compatibility problems that need fixing ASAP.  until the developer updates have to make do with the default phone.

**Comment by BTNGaming** [comment] 2021-09-10 21:00
I will be fixing ALL of these issues in the nearISH future, I'm currently working on my server build, and when that launches, this phone will be getting a MASSIVE overhaul. As far as phone to phone calls, it will require the phone item called 'phone' in your inventory and theirs, There is no compatibility issue with the ambulance job because that hasn't changed since 1.2 ESX. This phone DOES work with ESX 1.2 Legacy, including Lindens fixes and bug adjustments and such. I know this because I use it personally, as well as he has used it, and so many others as well.

I would remove ALL database info of GCPhone, reinstall it, (from the releases page directly, NOT the github main page version), reinstall the database, make sure you're using 1.2 version, and if it's still causing issues. Specify what all issues you have with it and I can try to help you out with that!

**Comment by Adrianmcmastergaming** [comment] 2021-09-10 21:29
We still cannot call one another using the framework esx 1.2 legacy. I have spoken to others who use legacy and say they are having the exact same problem as us.  I can see in the comments a few have the same problem as well. We are all stuck with no phone to use. We can send texts and GPS to the ambulance. It's just the trigger for the phone calls.  We use Mumble_VoIP and know that it is working because we can use rp-radio and can hear one another.  And hear in normal roleplay voice talk as well. We also tried a converted qb_phone_deluxe and that works and can send phone calls folks can see the phone pop up answer but cannot hear one another so e know it's the deluxe phone as well that has a problem. We went back with reignited 1.2 for now but cannot make any calls.  There is no other phone out there that works as we have tried them all and now ran out of ideas. We are now hoping that you can solve this problem for us as a lot would appreciate it.  I have also search youtube for gc reignited for on how to correctly use it but all the video's are for the older framework. Is it possible you could do a video on how to properly set up and use reignited phone with mumble-voip and esx 1.2 Legacy because I know a lot of folks would appreciate it. We are probably missing something.  Is there anything that has to be added to the server.cfg for example set voice. Beca\use I have searched google and can find nothing.

**Comment by JeffreyGerritsen** [comment] 2022-02-18 03:17
Same here, Cant make phone calls

**Comment by karovx** [comment] 2022-03-13 21:43
Phone calls doesn't work between players, can anyone help?

**Closed** 2022-05-01 17:53 UTC
