### ISSUE TITLE
Police and ambulance can see your location without sending gps coords

### ISSUE THREAD

**Issue by argykaraz** [Re-Ignited-Development/Re-Ignited-Phone#39] opened 2020-09-21 00:05 UTC
When a player sends a message to either Police or Ambulance, every member of the service can see this players location.. Forever!
The message can be anything. This should not happen I believe.
If this is by default, then we should have the option to disable it, or at least minimize the time shown.
This should actually work like a normal contact, where you have to share willingly your location.

To clarify:
- A player sends a message (with any text) to "ambulance" service (or police).
Then all members of said service (ambulance or police) can see the players location, forever.

**Comment by RockySouthpaw** [comment] 2020-09-25 22:38
Can confirm this is for any message sent to a job. Super game breaking.
![QIV22yCUH4](https://user-images.githubusercontent.com/55056068/94321668-4baf2680-ff5e-11ea-9bbe-b92e4c0a5346.png)

Added to trello

**Comment by RockySouthpaw** [comment] 2020-09-26 01:48
Issue was the result of this commit:
https://github.com/Re-Ignited-Development/Re-Ignited-Phone/commit/6291c42d199e0b924561d0bfb7030f2172dc2c2e

Issue isn't prevalent in earlier commits until this one.

**Comment by RockySouthpaw** [comment] 2020-09-30 17:57
Accidently closed. Fixed.

**Comment by RockySouthpaw** [comment] 2020-10-02 18:08
A temporary fix is the following:

**Config.lua**
Add: `Config.ShareRealtimeGPSJobTimer = 10 -- Default Job GPS Timer (Minutes)`

**esxaddonsgcphone-s.lua**
Find where `alert.source.then` is and replace it with this:
```lua
if alert.source then
              if messText == 'GPS Live Position' then
                local duration = Config.ShareRealtimeGPSJobTimer * 60000 --Config Time (Default = 10 minutes)
                TriggerClientEvent('gcPhone:receiveLivePosition', targetPlayer, alert.source, duration, alert.numero, 1)
              end
           end
```

This will make it so every message sent to jobs no longer does the GPS stuff and will only activate it if they send the job their location. It's currently independent of what the actual result is for gps live tracking, but I'm working on fixing it as i need to pass `timeString` from server.lua to esxaddonsgcphone.lua.

**Comment by RockySouthpaw** [comment] 2020-10-25 22:42
Applied temporary fix on latest release. Will find a better work around.

**Comment by RockySouthpaw** [comment] 2020-11-25 08:41
Closing for now since the issue is different at this point.

**Closed by RockySouthpaw** 2020-11-25 08:41 UTC
Labels: Major Issue, On Trello
